name: Bump Minor Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Bump version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version minor

      - name: Push changes
        run: |
          git push origin main
          git push --tags
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
